# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCvzxcz():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_cvzxcz(self):
    self.driver.get("https://dexscreener.com/solana/3kjdw8btsek54duygyirvjfwpmavh5kgq6si1retmjx5")
    self.driver.set_window_size(1936, 1056)
    element = self.driver.find_element(By.ID, "tabs-:R1d3l5hl5mlau:--tab-3")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".custom-1swyx69")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".custom-1swyx69")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".custom-1swyx69")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".custom-1swyx69")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".custom-1swyx69")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, ".custom-1swyx69")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.switch_to.frame(0)
    element = self.driver.find_element(By.CSS_SELECTOR, "#header-toolbar-screenshot svg")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.switch_to.default_content()
    element = self.driver.find_element(By.CSS_SELECTOR, ".custom-iztagb")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
